name: On Pull Request Review Comment

on:
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  handle-pr-review-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Show review comment details
        run: echo "A pull request review comment event was triggered!"
